---
# Install grafana agents
- name: Ensure o11y can be enabled in this host
  ansible.builtin.assert:
    quiet: true
    fail_msg: o11y is not supported in this host
    that:
      - (group_names|intersect(o11y_enabled_roles)|length>0)
  when: o11y_enable

- name: Agent directories
  ansible.builtin.file:
    path: "{{ o11y_agent_dir }}"
    state: "{{ 'directory' if o11y_enable else 'absent' }}"
    mode: "0644"
  loop: "{{ o11y_alloy_dirs }}"
  loop_control:
    loop_var: o11y_agent_dir

- name: Add Alloy Repo
  ansible.builtin.deb822_repository:
  args: "{{ item }}"
  loop: "{{ o11y_alloy_repo }}"

- name: Install Grafana Alloy
  ansible.builtin.package:
    name: "{{ alloy_pkg }}"
    state: present
  when: o11y_enable

- name: Creating a service file
  ansible.builtin.copy:
    dest: "{{ o11y_alloy_unit }}"
    mode: "0644"
    content: |
      [Unit]
      Description=Grafana Alloy  Service
      Requires=network.target
      After=network.target
      [Service]
      Type=simple
      ExecStart=/usr/bin/alloy run --storage.path {{ o11y_alloy_data_dir }}  --config.format alloy {{ o11y_alloy_data_dir }}
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
  when: o11y_enable

- name: Agent configuration for MAAS < 3.5
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: "{{ o11y_alloy_dir }}/agent.yaml"
    mode: "0644"
  when: o11y_enable and maas_version is version("3.5",'<')
  notify:
    - Convert Agent Config

- name: Agent configuration for MAAS 3.5
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: "{{ o11y_alloy_dir }}/agent.yaml"
    mode: "0644"
  when: o11y_enable and maas_version is version("3.5",'>=')
  notify:
    - Convert Agent Config

- name: Flush Handlers
  ansible.builtin.meta:
    free_form: flush_handlers
  when: o11y_enable
