---
- name: teardown | Set the grafana agent service status
  ansible.builtin.service:
    name: telemetry
    state: stopped
  when: ansible_facts.services['telemetry.service'] is defined

- name: teardown | Remove o11y agent artifacts
  ansible.builtin.file:
    state: absent
    name: "{{ agent_dir }}"
  loop: "{{ o11y_grafana_agent_dirs | union([o11y_grafana_agent_unit]) }}"
  loop_control:
    loop_var: agent_dir
