---
# Installs MAAS

- name: teardown | Uninstall MAAS - Snap
  community.general.snap:
    name: maas
    state: absent

- name: teardown | Uninstall MAAS - Deb
  ansible.builtin.apt:
    name: maas-region-api
    purge: true
    state: absent

- name: teardown | Remove MAAS Files
  ansible.builtin.file:
    path: "{{ maasfile }}"
    state: absent
  loop:
    - /var/snap/maas/
    - /var/lib/maas/
    - /etc/maas/
  loop_var: maasfile
