---
- name: teardown | Uninstall MAAS - snap
  community.general.snap:
    name: maas
    state: absent

- name: teardown | Uninstall MAAS - deb
  ansible.builtin.apt:
    name:
      - maas-rack-controller
    purge: true
    state: absent
