---
all:
  vars:
    maas_version: "3.3"
    maas_postgres_password: pg_admin
    maas_installation_type: snap
    maas_url: http://10.0.20.100:5240/MAAS
    admin_username: admin
    admin_password: admin
    admin_email: alan.janis@icloud.com
    maas_proxy_postgres_proxy_enabled: false
    enable_tls: false
    enable_firewall: true
    vault_integration: false
    # vault_url:
    # vault_approle_id:
    # vault_wrapped_token:
    # vault_secrets_path:
    o11y_enable: true
    o11y_prometheus_url: http://10.0.20.100:9090/api/v1/write
    o11y_loki_url: http://10.0.20.100:3100/loki/api/v1/push
    o11y_alertrules_dest: ./maas_local/alertrules
    maas_backup_download_path: ./maas_local/backups
    maas_postgres_floating_ip_prefix_len: 24
    maas_postgres_floating_ip: 10.0.20.110
    maas_postgres_primary: "{{ groups['maas_postgres'][0] }}"

  children:

    maas_postgres:
      hosts:
        maas-aio-01:
          ansible_host: 10.0.20.100
    # maas-pg01:
    # maas-pg02:
    # maas-pg03:

    maas_postgres_primary:
      hosts:
        maas-aio-01: {}

    maas_region_controller:
      hosts:
        maas-aio-01: {}
        # maas-region01:
        # maas-region02:
        # maas-region03:

    maas_rack_controller:
      hosts:
        maas-aio-01: {}
    # maas-region01:
    # maas-rack01:
    # maas-rack02:

    maas_proxy:
      hosts:
        maas-aio-01: {}
    # maas_postgres_proxy:
    # hosts:
    #   maas-region01:
    maas_pacemaker:
      children:
        maas_corosync:
          hosts:
            maas-aio-01: {}
          # hosts:
          #   maas-pg01:
          #   maas-pg02:
          #   maas-pg03:
