---
- name: teardown | Uninstall HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: absent
    purge: true

- name: teardown | Remove HAProxy artifacts
  ansible.builtin.file:
    state: absent
    name: "{{ haproxy_artifact }}"
  loop:
    - /etc/haproxy/haproxy.cfg
    - /var/lib/haproxy
  loop_var: haproxy_artifact
