---
# firewall config for maas. First lock down everything except port 22
- name: setup_firewall_rules | Install persistent iptables package
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: setup_firewall_rules | Allow outgoing connection port 22 (ssh)
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: setup_firewall_rules | Allow local traffic
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: setup_firewall_rules | Allow incoming port 22
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: setup_firewall_rules | Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: setup_firewall_rules | Allow port 53 tcp/udp
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 53
    jump: ACCEPT

- name: setup_firewall_rules | Allow port 53 tcp/udp
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 53
    jump: ACCEPT

- name: setup_firewall_rules | Open tcp ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ tcp_port }}"
    jump: ACCEPT
  loop:
    - "{{ maas_pg_tcp_ports | default([]) | select() }}"
    - "{{ maas_pgproxy_tcp_ports | default([]) | select() }}"
    - "{{ maas_proxy_tcp_ports | default([]) | select() }}"
    - "{{ maas_rack_tcp_ports | default([]) | select() }}"
    - "{{ maas_region_tcp_ports | default([]) | select() }}"
  loop_var: tcp_port

- name: setup_firewall_rules | Open udp ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: "{{ udp_port }}"
    jump: ACCEPT
  loop:
    - "{{ maas_pg_udp_ports | default([]) | select() }}"
    - "{{ maas_pgproxy_udp_ports | default([]) | select() }}"
    - "{{ maas_proxy_udp_ports | default([]) | select() }}"
    - "{{ maas_rack_udp_ports | default([]) | select() }}"
    - "{{ maas_region_udp_ports | default([]) | select() }}"
  loop_var: udp_port

- name: setup_firewall_rules | Set policy for INPUT chain to drop (otherwise)
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: setup_firewall_rules | Set policy for FORWARD chain to drop
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP

- name: setup_firewall_rules | Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  changed_when: false
