---
# Remove iptables rules as part of teardown

- name: teardown | Set policy for INPUT chain to accept
  ansible.builtin.iptables:
    chain: INPUT
    policy: ACCEPT

- name: teardown | Set policy for FORWARD chain to accept
  ansible.builtin.iptables:
    chain: FORWARD
    policy: ACCEPT

- name: teardown | Flush all other rules
  ansible.builtin.iptables:
    flush: true

- name: teardown | Remove persistent iptables package
  ansible.builtin.apt:
    name: iptables-persistent
    state: absent
