---
- name: backup | Ensure psycopg2 pip module is installed
  ansible.builtin.pip:
    executable: pip3
    name: psycopg2
    state: present

- name: backup | Ensure remote postgres backup directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ maas_postgres_backup_dir }}"
    mode: "0777"

- name: backup | Dump an existing database to a file (with compression)
  community.postgresql.postgresql_db:
    name: "{{ maas_postgres_database }}"
    state: dump
    login_host: "{{ groups['maas_postgres'][0] }}"
    target: "{{ maas_postgres_backup_path }}"
    login_user: "{{ maas_postgres_user }}"
    ssl_mode: disable
    login_password: "{{ maas_postgres_password }}"
  register: maas_pg_dump
  until: maas_pg_dump is success
  become: true

- name: backup | Stat pg_dump archive
  ansible.builtin.stat:
    path: "{{ maas_postgres_backup_path }}"
  register: maas_pg_archive
  when: maas_pg_dump is success

- name: backup | Print archive file information
  ansible.builtin.debug:
    msg: |
      Exists: {{ maas_pg_archive.stat.exists }}
      Path: {{ maas_pg_archive.stat.path }}
      File Size: {{ maas_pg_archive.stat.size }}
      Checksum: {{ maas_pg_archive.stat.checksum }}
  when: maas_pg_dump is success
