---
- name: teardown | Set postgres number for uninstall
  ansible.builtin.set_fact:
    maas_postgres_version_number: "{{ 14 if ansible_distribution_major_version | float >= 22 and maas_version is version('3.2', '>=') else 12 }}"

- name: teardown | Setting config dirs for uninstall
  ansible.builtin.set_fact:
    maas_postgres_config_dir: /etc/postgresql/{{ maas_postgres_version_number }}/main/

- name: teardown | Stop Postgres metrics agent
  ansible.builtin.service:
    name: postgres_exporter
    state: stopped
  when: ansible_facts.services['postgres_exporter.service'] is defined

- name: teardown | Remove PostgreSQL artifacts
  ansible.builtin.file:
    state: absent
    name: "{{ pg_artifact }}"
  loop:
    - /opt/pgsql_check
    - /etc/xinetd.d/pgsql_check
    - /etc/systemd/system/postgres_exporter.service
    - "{{ o11y_postgres_exporter_dir }}"
  loop_control:
    loop_var: pg_artifact

- name: teardown | Uninstall PostgreSQL and configuration dependencies
  ansible.builtin.apt:
    name:
      - "{{ maas_postgres_deb_name | default('postgresql-' ~ maas_postgres_version_number) }}"
      - acl
      - python3-psycopg2
      - xinetd
    state: absent
    purge: true
