---

- name: backup | Generate List of Archiveable Directories
  vars:
    archive: []
  ansible.builtin.set_fact:
    archive_list: "{{ archive + [item] }}"
  loop:
    - "{{ ('maas_postgres_primary' in group_names) | ternary('{{ maas_postgres_backup_dir }}', '') }}"
    - "{{ (('maas_region_controller' in group_names) or ('maas_rack_controller' in group_names)) | ternary('{{ maas_config_backup_path }}', '') }}"
    - "{{ (('maas_region_controller' in group_names) or ('maas_rack_controller' in group_names)) | ternary('{{ maas_runtime_backup_path }}', '') }}"
  when: item

- name: backup | Print backup archives to create
  ansible.builtin.debug:
    msg: "{{ item }}"
  when: item is defined
  loop: "{{ archive_list }}"

- name: backup | Bundle Backup Assets
  community.general.archive:
    path: "{{ item }}"
    mode: "0644"
    exclude_path:
      - "{{ maas_exclude_backup_path }}"
    dest: "{{ maas_backup_dest_path }}"
  loop: "{{ archive_list }}"
  register: backups_created
  when: archive_list is defined

- name: backup | Stat archives created
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  when: backups_created is defined
  loop: "{{ backups_created.results }}"

- name: backup | List archives created
  ansible.builtin.debug:
    msg: "{{ item.dest }}"
  when: backups_created is defined
  loop: "{{ backups_created.results }}"

- name: backup | Download Backup
  ansible.posix.synchronize:
    mode: pull
    dest: "{{ maas_backup_download_path }}/{{ item.dest | basename }}"
    src: "{{ item.dest }}"
    delete: true
  loop: "{{ backups_created.results }}"
  when: item
