---
- name: restore | Create Temporary Unpack Directory
  ansible.builtin.file:
    path: /tmp/maas_backup/
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: restore | Unpack Backup Archive
  ansible.builtin.unarchive:
    src: "{{ maas_backup_file }}"
    dest: /tmp/maas_backup/

- name: restore | Stop Region Controller
  ansible.builtin.systemd:
    name: maas-regiond.service
    state: stopped
  when: ('maas_region_controller' in group_names) and maas_install_deb | bool

- name: restore | Stop Rack Controller
  ansible.builtin.systemd:
    name: maas-rackd.service
    state: stopped
  when: ('maas_rack_controller' in group_names) and maas_install_deb | bool

- name: restore | Stop MAAS snap
  ansible.builtin.command: snap stop maas
  when: (('maas_region_controller' in group_names) or ('maas_rack_controller' in group_names)) and (not maas_install_deb | bool)
  register: snap_stop
  changed_when: snap_stop is changed

- name: restore | Restore Config
  ansible.builtin.command: mv /tmp/maas_backup/etc/maas {{ maas_restore_config_path }}
  when: ('maas_region_controller' in group_names) or ('maas_rack_controller' in group_names)
  register: restore_config
  changed_when: restore_config is changed

- name: restore | Restore Runtime Data
  ansible.builtin.command: mv /tmp/maas_backup/var/lib/maas {{ maas_restore_runtime_path }}
  when: ('maas_region_controller' in group_names) or ('maas_rack_controller' in group_names)
  register: runtime_data
  changed_when: runtime_data is changed

- name: restore | Start Region Controller
  ansible.builtin.systemd:
    name: maas-regiond.service
    state: started
  when: ('maas_region_controller' in group_names) and maas_install_deb | bool

- name: restore | Start Rack Controller
  ansible.builtin.systemd:
    name: maas-rackd.service
    state: started
  when: ('maas_rack_controller' in group_names) and maas_install_deb | bool

- name: restore | Start MAAS snap
  ansible.builtin.command: snap start maas
  when: (('maas_region_controller' in group_names) or ('maas_rack_controller' in group_names)) and (not maas_install_deb | bool)
  register: snap_start
  changed_when: snap_start is changed
