---
- name: teardown | Uninstall Corosync
  ansible.builtin.apt:
    name: corosync
    state: absent
    purge: true
    autoremove: true

- name: teardown | Remove Corosync artifacts
  ansible.builtin.file:
    state: absent
    name: "{{ corrosync_artifacts }}"
  loop:
    - /etc/corosync/corosync.conf
  loop_control:
    loop_var: corrosync_artifacts
